# Learn 20 Numpy keywords in 2 Minutes for Beginners

####  Author Social Media: @sagarsharma4244

The minimum requirement to do deep learning and become a data scientist is libraries  like numpy, scipy, matplotlib etc.
We use numpy for creating, manipulating  matrices which are used in neural networks.

In [3]:
import numpy as np

## Creating Array

### Add elements to an array 

In [5]:
# Add Integers to Array
np.array( [ 1, 2, 3 ] )

array([1, 2, 3])

In [6]:
# Add Float to Arrays
np.array( [ 1.5, 2, 3 ] )

array([1.5, 2. , 3. ])

###  Array with a range

In [7]:
# Array with a limit range
np.arange( 15 )

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# Array with a Start & limit
np.arange( 2, 15 )

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

##  Creating Matrices

### Create & Add elements to matrix

In [9]:
# Create & Add elements to matrix
np.matrix( [ [1, 2], [3, 4], [2, 5] ] )

matrix([[1, 2],
        [3, 4],
        [2, 5]])

### Reshape array to matrix

In [12]:
np.arange(15).reshape(3, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

### Shape of a matrix

In [4]:
a = np.arange(15).reshape(3, 5)

#Find the shape of matrix
a.shape

(3, 5)

### Dimension of a matrix

In [14]:
#Find the dimension of matrix
a.ndim

2

In [15]:
#Find the size of matrix
a.size

15

In [5]:
#Find the data type of matrix
a.dtype.name

'int32'

In [18]:
#Create a Zero matrix
np.zeros( ( 3, 2 ) )

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [20]:
#Create a One's matrix
np.ones( ( 2, 3 ) )

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#Create a Identity matrix
np.eye( 3 )

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [6]:
# Create an array with interval
np.arange( 10, 100, 5 ) 

array([10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85, 90,
       95])

In [28]:
# Create an array within limits with total elements 10
np.linspace( 10, 100, 10 )

array([ 10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [30]:
#Create a matrix with random Elements
np.random.rand( 3, 2 )

array([[0.94512244, 0.66431729],
       [0.137442  , 0.06496045],
       [0.87679875, 0.99479091]])

In [33]:
a = np.random.rand( 3, 2 )

#Transpose of a Matrix
a.T

array([[0.41084903, 0.97842447, 0.24900103],
       [0.350679  , 0.63566364, 0.33958258]])

##  Maths

###  Dot Product

In [37]:
b = np.matrix([[1, 2], [3, 4], [2, 5]])
c = np.matrix([[1, 2,8], [3, 4,2]])

# Dot Product
np.dot( b, c )


matrix([[ 7, 10, 12],
        [15, 22, 32],
        [17, 24, 26]])

In [8]:
b = np.matrix( [  [ 1, 2 ], [ 3, 4 ] ] )
# Sum of Matrix
b.sum()

10

In [9]:
# Add all elements in matrix
b.sum(axis=1)

matrix([[3],
        [7]])

In [44]:
b = np.matrix( [ [ 1, 2 ], [ 3, 4] ] )
c = np.matrix( [ [ 5, 6 ], [ 7, 8] ] )
# Add two Matrix
np.add( b, c )

matrix([[ 6,  8],
        [10, 12]])

In [46]:
b = np.matrix( [ [ 1, 2 ], [ 3, 4] ] )
# Minumum Value in matrix
b.min()

1

In [47]:
# Maximum Value in matrix
b.max()

4

In [49]:
b = np.matrix( [ [ 1, 2 ], [ 3, 4] ] )

#Squareroot of matrix
np.sqrt(b)

matrix([[1.        , 1.41421356],
        [1.73205081, 2.        ]])

In [50]:
# Iterate elements in Array
for row in b: 
       print( row ) 

[[1 2]]
[[3 4]]


In [52]:
b = np.matrix( [ [ 1, 2 ], [ 3, 4 ] ] )

#Flatten a matrix
b.flatten()

matrix([[1, 2, 3, 4]])

In [54]:
#Floor
b = np.matrix( [ [ 1.5, 2.8 ], [ 3.45, 4.1 ] ] )
np.floor( b )

matrix([[1., 2.],
        [3., 4.]])

In [55]:
# Split array into parts
a = np.arange( 15 )
np.split( a, 5 )

[array([0, 1, 2]),
 array([3, 4, 5]),
 array([6, 7, 8]),
 array([ 9, 10, 11]),
 array([12, 13, 14])]

In [56]:
# Join Multiple Arrays
b = np.matrix( [ [ 1, 2 ], [ 3, 4] ] )
c = np.matrix( [ [ 5, 6 ], [ 7, 8] ] )

# Concatenate Arrays
np.concatenate((b,c), axis=0)

matrix([[1, 2],
        [3, 4],
        [5, 6],
        [7, 8]])

In [57]:
# Concatenate Arrays
np.concatenate((b,c), axis=1)

matrix([[1, 2, 5, 6],
        [3, 4, 7, 8]])